---
image: docker:stable

services:
- name: docker:dind
  command: ["--experimental"]

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  # Enable experimental features in Docker client
  - mkdir $HOME/.docker
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # login to gitlab ci
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --squash --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE:latest
    # add tag if available
    - if [[ ! -z $CI_BUILD_REF_NAME ]]; then docker tag $CONTAINER_IMAGE:$CI_COMMIT_SHA $CONTAINER_IMAGE:$CI_BUILD_REF_NAME; fi
    - if [[ ! -z $CI_BUILD_REF_NAME ]]; then docker push $CONTAINER_IMAGE:$CI_BUILD_REF_NAME; fi
